### ISSUE TITLE
Suggestion - Configurable Paleobotanist / Paleobotanist Home

### ISSUE THREAD

**Issue by TorgoApproves** [AechtRob/PrehistoricFlora#1]
First off, I ADORE your mod, it's easily one of the best mods I've ever used and it adds surprisingly so much and I honestly cannot imagine playing without it at this point :) I'm currently working on a mod-pack and would love to use your mod, however due to the theme and feel that I am shooting for, I unfortunately cannot update to v.48 for the time being because the new villager and their house cannot be disabled from spawning in villages :/ As such, I was hoping to make a little suggestion for a future release of the mod, I was hoping that you could add an option in the config file to perhaps disable one or both of the villager and their home, or perhaps even an option to modify their spawning frequency to however the player sees fit :) I understand though that that sort of thing is probably way harder to implement than it seems, and I'll definitely still love the mod and download it either way c: (For reference though, I do know that some mods, like Immersive Engineering, do have something like what I'm suggesting, and while I'm not saying we should steal from their code... you know, maybe there's some ideas there ;p) Thank you all so much for hearing me out, and thank you for your wonderful beautiful mod :)

Ps. It's way better than F&A at this point imo c;

**Comment by AechtRob** [comment]
I think that's a great idea. But I don't know yet how "common" the time reversal enchantment is on the enchanting table: I'd like to know that it was feasibly obtainable without the villager.

**Comment by AechtRob** [comment]
The Palaeobotanist village house is now (v.48.1) configurable in frequency in a village. I am not yet sure whether the villager himself will be present in villages without a house. It may be that the vanilla village picks random villagers from the available pool of trades, and still generates him sometimes without the house. Please feed back if you need to.
